Add transformers `Map<K,V>.havingKeys()` and `Map<K,V>.havingValues()`
assertk-org/assertk pull request #557
Opened 2024-11-15 02:22 UTC by HaydenMeloche

This adds some transformers allowing you to utilize `Collection` asserts on parts of a map.

Example for keys:
```kotlin
assertThat(mapOf("key" to "value")).havingKeys().containsOnly("key")
```
Example for values: 
```kotlin
assertThat(mapOf("key" to "value")).havingValues().containsOnly("value")
```

Given that there is already a `Map<K,V>.isNotEmpty()` I thought it made sense to have these transformers throw an error if their corresponding parts have no values.

fixes #527

2024-11-15 05:41 UTC, JakeWharton commented
> I thought it made sense to have these transformers throw an error if their corresponding parts have no values.

Do any other "having"-style functions also perform an implicit assertion?

Really my only criticism of this approach is that there's something pure in the "having" suite of functions being purely transformational in contrast to actual validation functions. There's nothing _strictly_ wrong with doing `assertThat(map).havingKeys().isEmpty()`, after all, even if it's a bit redundant.

2024-11-15 15:30 UTC, JakeWharton commented
I did find some examples, such as `key` on a map (which should become `havingKey` if #522 moves forward). So retaining the implicit assertion here seems fine 👍 .

2024-11-15 15:38 UTC, HaydenMeloche commented
@JakeWharton I admittedly was on the fence here (and I'm definitely open to removing the assertion). `Map<K,V>.key()` was ultimately the reason I decided to leave in the assertion

2024-12-14 15:19 UTC, jzbrooks commented
This seems analogous to #546 (function names in that PR notwithstanding).

2025-04-21 13:01 UTC, emartynov requested changes
One comment and the rest is LGTM

2025-04-21 13:01 UTC, emartynov commented on assertk/src/commonTest/kotlin/test/assertk/assertions/MapTest.kt
> +            assertThat(emptyMap<String, String>()).havingKeys()
Should it be `havingValues()`?

2026-09-15 19:28 UTC, closed without merging